### ISSUE TITLE
README.md suggestion

### ISSUE THREAD

**Issue by rbenzeev** [windnage/wgms-glacier-project#2]
@windnage 
Your README includes some really great descriptions of your data used and of the files in your repo. However, I would like to see you describe a little more background and/or context for your project. For example, why are these glacier statistics important? Who will use this data? Who is your intended audience? Perhaps also provide one-sentence descriptions explaining a little background of WGMS, GLIMS, and RGI. Great work!

**Comment by windnage** [comment]
@rbenzeev I've addressed this issue. I've added a Background section to my readme to explain the importance of the glacier statistics and my intended audience along with a short description of the WGMS. To the Data Used section, I added descriptions of my data sources (GLIMS, RGI, and GTN-G glacier region).
