### ISSUE TITLE
Suggestion on notebook naming conventions

### ISSUE THREAD

**Issue by rbenzeev** [windnage/wgms-glacier-project#3]
@windnage 
For clarity, it might be useful to change the names of your notebooks so that each starts with a unique identifier. Currently, two notebooks start with the word "clean" and another two start with the word "explore". This might end up being confusing for another user.

**Comment by windnage** [comment]
@rbenzeev I've updated the notebooks with a new naming convention to make them easier to tell what is what and in what order to run them.

Naming convention:

x-operation-data.ipynb 

Where:

**x**: A counter for the order that the notebooks should be run in (0 means that the notebook is not required for

**operation**: The processing that is applied to the data in the notebook (clean, compare, explore, or split)

**data**: The data that is processed in the notebook (gtng, glims, or rgi)

Thanks for you comments!
-Ann
